### ISSUE TITLE
Create a new table for managing sybil addresses in the backend

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1303]
Right now, we only have one tag "known sybil"... but each round will; have its own sybil address set, and they will not always be the same and we should not always punish an address for multiple rounds if they were sybil in one...

This is the list of sybil addresses we have so far: https://docs.google.com/spreadsheets/d/1eUHSmPJ1QaWWWFeVcxYQJBtfnPIzxiWicylxBaZ2d3M/edit#gid=1145721990

We should create some system for seeing "all sybils" OR "sybils from JUST giving season"

**Comment by jainkrati** [comment]
Thanks for assigning me @MoeNick .  Could you move this to Impact Graph

**Comment by MoeNick** [comment]
I moved it to impact-graph @jainkrati

**Comment by CarlosQ96** [comment]
I can take this, ill have to add a middle table between qfround and user and the inner join it.

**Comment by laurenluz** [comment]
is this something @maryjaf can test @CarlosQ96 @jainkrati ?

soon we'll need to make a list of sybil addresses for polygon & get them in the db. I also want to make sure that we are making the appropriate adjustments to the "export QF round data" button in admin bro, so that it is eliminating "known sybils" from that QF round only.

how do we manage these lists? is there something in admin bro now?

**Comment by CarlosQ96** [comment]
@maryjaf in the adminJs there is a new entity called Sybil you can add items to the list and filter them. Can be tested that way. When generating the qfround data from the qfround tab => button, it will exclude them.

The csv import/export is another issue. As that takes more time.

**Comment by maryjaf** [comment]
I've sent a request for access to this google sheet  to complete the test
@laurenluz 

https://docs.google.com/spreadsheets/d/1eUHSmPJ1QaWWWFeVcxYQJBtfnPIzxiWicylxBaZ2d3M/edit#gid=1145721990

**Comment by laurenluz** [comment]
@CarlosQ96 is this already on production? because I think the spreadsheet only populates w/ data from prod, not staging...

is there a separate "master" sheet for staging? or actually, is it the same spreadsheet as this one? https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1770697429

**Comment by maryjaf** [comment]
I did these steps but I couldn't see the expected result 
please check the scenario,did I do the right flow ?

-roundId : 77 

-I created a new sybil record with this data 

 qfRoundId,walletAddress
77,0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8
77,0xD5db3F8B0a236176587460dC85F0fC5705D78477

-donated with this wallet address that there wasn't in a sybil records (0xcd192b61a8Dd586A97592555c1f5709e032F2505)

-donated with this wallet address that there was in a sybil records (0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8)

-after the round ended, I taped on "return all donation data " in QF round menu for round 77 (sybil_test_round_77)

-a new sheet was added to the google sheet but there was no record in this sheet 
I expected the donation with (0xcd192b61a8Dd586A97592555c1f5709e032F2505) would be shown in this sheet and only (0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8) be excluded from sheet

please take a look @CarlosQ96  


<img width="1574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05pQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb579d567698a9297fe7938b6232fdb47b1562e1/image.png" alt="image.png" />

**Comment by laurenluz** [comment]
here are the steps I think you'd need to follow:
- create the round w/ a short duration
- add at least 2 projects to the round
- donate to those projects from a few different addresses (like project A from wallet A & B... project B from wallet A B & C)... make sure that all the wallets have a verified gitcoin passport score above the set threshold for round, and are not part of the "purple list"
- then, when the round is over... make wallet B a "known sybil for that particular qf round"
- then export the data to the spreadsheet

Then, the expected result should be that you see 2 entries on the spreadhseet, one for project A and project B. On the line or project A, you should see 2 total donors, 1 unique donor. For project B, you should see 3 total donors, 2 unique donors.

That would be the expected behaviour.

**Comment by maryjaf** [comment]
Thanks @laurenluz 
Yeah
-I created round 77(sybil_round_01)  for this test and added 3 projects 
-Donated to these 2 projects with users (one of these users is set on sybil record and another not) 
with score more than 1 (minimum score was set 1 in admin bro for this round )

https://staging.giveth.io/project/testupdate1000?tab=donations
https://staging.giveth.io/project/mejan?tab=donations

<img width="1387" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/eaeee6df-7e9e-4eeb-8bb1-2699c3a9bf53">
<img width="1350" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/534463ac-3e7e-4c53-b8b9-7b106d9ca604">

**Comment by laurenluz** [comment]
and they were not "purple" list addresses? like these donors addresses were not also used somewhere on Giveth staging as a recipient address for a project? @maryjaf 

becaues if they were, then it would explain why they're not showing up too.

**Comment by maryjaf** [comment]
> and they were not "purple" list addresses? like these donors addresses were not also used somewhere on Giveth staging as a recipient address for a project? @maryjaf
> 
> becaues if they were, then it would explain why they're not showing up too.

Thanks @laurenluz I didn't consider the purple list, I'll check and let you know

**Comment by maryjaf** [comment]
I've checked and the previous problem was related to purple list, thanks @laurenluz 

I've faced new problem please take a look @CarlosQ96 @mohammadranjbarz 

I set 0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8 as a sybil record for round 80 
But the donation related to this account is shown in round's donation list 

https://impact-graph.serve.giveth.io/admin/resources/Sybil/records/15/show
https://staging.giveth.io/project/mejan?tab=donations
<img width="1292" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/2687f044-a7e8-4374-a507-6e48b0270f77">
<img width="1371" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/db4265d6-70c1-4eff-9a03-6f8cef90b284">

**Comment by maryjaf** [comment]
we checked 

> I set 0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8 as a sybil record for round 80
> But the donation related to this account is shown in round's donation list

We have checked this with @mohammadranjbarz and this problem occurs because there was another record in sybil menu for this round and by adding the new record, the new changes wouldn't be applied

**Comment by mohammadranjbarz** [comment]
> we checked
> 
> > I set 0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8 as a sybil record for round 80
> > But the donation related to this account is shown in round's donation list
> 
> We have checked this with @mohammadranjbarz and this problem occurs because there was another record in sybil menu for this round and by adding the new record, the new changes wouldn't be applied

You can test it now, I fixed it

**Comment by maryjaf** [comment]
> You can test it now, I fixed it

I tried to set a new sybil record with this data:
qfRoundId,walletAddress
80,0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8
but no record has been added

**Comment by maryjaf** [comment]
> > You can test it now, I fixed it
> 
> I tried to set a new sybil record with this data: qfRoundId,walletAddress 80,0x7F37e3008207C27360b20ABCFB5fdCc8e37596B8 but no record has been added

This problem has been resolved 
after checking on prd for QF polygon this issue could be closed

**Comment by jainkrati** [comment]
@maryjaf pls close this as completed given you have tested it.

**Comment by maryjaf** [comment]
It should be checked for a closed round, I think @laurenluz could approve that it works correctly on prod for previous rounds like as the result on stg

**Comment by jainkrati** [comment]
@laurenluz could you please verify and close this issue.

**Comment by laurenluz** [comment]
@mohammadranjbarz @CarlosQ96 - what's this mean here? 
![image](https://github.com/Giveth/impact-graph/assets/75490971/9b08a405-8457-46bf-b602-b138d4c42355)

does it mean that all of the sybil addresses we had marked as "known sybils" in the past are now erased w/ the introduction of the table to managing sybils per round?

**Comment by jainkrati** [comment]
@mohammadranjbarz can you share the documentaiton link here

**Comment by laurenluz** [comment]
I see a bunch of issues on this! here is the documentation link: https://github.com/Giveth/impact-graph/blob/staging/docs/qfRoundInstruction.md#mark-users-as-sybil-for-qfround

- what is the "userID"? in the dropdown, I see a bunch of blanks + some random weird emails at the bottom. email should absolutely not be the way be select users to flag as sybils!
![image](https://github.com/Giveth/impact-graph/assets/75490971/f7ac8969-b805-4609-aaaf-d2821b79c0e7)

- I get nothing but errors when I try to import csvs...
![image](https://github.com/Giveth/impact-graph/assets/75490971/a4a64585-facb-47d0-b85b-38f75003eea2)
![image](https://github.com/Giveth/impact-graph/assets/75490971/565c01b1-c3e2-4c13-97e4-27c3f4ee811c)

or when, I try to import the csv w/ no title row...

![image](https://github.com/Giveth/impact-graph/assets/75490971/38d3a552-fcbb-4e08-9e0f-a0899024ef0b)

@mohammadranjbarz @jainkrati

**Comment by MoeNick** [comment]
@jainkrati 
I think this needs re-assignments. or a quick meeting.

**Comment by mohammadranjbarz** [comment]
> @jainkrati I think this needs re-assignments. or a quick meeting.

@MoeNick  I fixed it yesterday and release a hotfix on production for that

<img width="1415" alt="Screenshot 1402-12-13 at 3 54 11 in the afternoon" src="https://github.com/Giveth/impact-graph/assets/9850545/a7900718-8be6-42bf-a62f-abe06118f776">


and I added the sybil addresses that @laurenluz had mentioned

**Comment by divine-comedian** [comment]
@laurenluz  - needs to review if it is fixed & close this one

**Comment by laurenluz** [comment]
@mohammadranjbarz this still doesn't work for me, I can't manually add the sybils, I just get errors and there is the same issue about adding the address.

it's create that you imported the addresses for me, but I would love to fix this so I don't need to keep bugging you.

can we please make it so that I (an admin) can flag a *donor address* as a "known sybil", and add it that way?

**Comment by laurenluz** [comment]
for example, I don't understand how I'm supposed to find a user ID to mark as the sybil... it should be the donor *Address* 
![image](https://github.com/Giveth/impact-graph/assets/75490971/ca319bce-960c-434d-bd24-1769ff4f4c2b)

**Comment by jainkrati** [comment]
@mohammadranjbarz i think the documentation is not enough. Probably video recordings would be helpful. Pls create and add links in the document you created.

**Comment by jainkrati** [comment]
@maryjaf pls test and share video

**Comment by maryjaf** [comment]
> share video

I think @mohammadranjbarz and @laurenluz had a call for this 
Do we still need this video?

**Comment by laurenluz** [comment]
hmm well we didn't have a call, but some improvements were made to the import feature and now I know how to use it 😅 

the advantage of good documentation is that then other people have somewhere to look that has clear information... instead of the information just being in the heads of a few contributors.

**Comment by maryjaf** [comment]
> @maryjaf pls test

I left a comment on the this [pull request](https://github.com/Giveth/impact-graph/pull/1391#issuecomment-1978937509
) about the result of test 

The problems related to adding record in sybil has been resolved only I asked a question and I think it was accepted from Lauren's point of view

**Comment by maryjaf** [comment]
> the advantage of good documentation is that then other people have somewhere to look that has clear information... instead of the information just being in the heads of a few contributors.

I realized that a more technical document was needed
If so, I think it is better to assign this to the developers

**Comment by jainkrati** [comment]
@mohammadranjbarz based on your last call with Lauren on this, whats the next step?

**Comment by mohammadranjbarz** [comment]
It's done and works well, I think we can close it, @maryjaf  @laurenluz  WDYT?
FYI @jainkrati

**Comment by laurenluz** [comment]
let's go!
