### ISSUE TITLE
Run migration files as JS files instead of TS

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#651]

**Comment by jainkrati** [comment]
@mohammadranjbarz is this solved by the PR you linked? if not, let @Meriem-BM progress on this further.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz is this solved by the PR you linked? if not, let @Meriem-BM progress on this further.

No it's not solved(I read the related PR it seems unrelated to this) but I think https://github.com/Giveth/impact-graph/issues/1481 can be a better (easier with bigger impact issue) one for Meriem,  WDYT?

**Comment by jainkrati** [comment]
@mohammadranjbarz pls guide Ali Ebrahmi to take this up

**Comment by mohammadranjbarz** [comment]
> Automatically

Cool, I messaged him in DM will schedule a call about this issue

**Comment by mohammadranjbarz** [comment]
@ae2079 
This lie in package.json do the job, please modify it to run migrations as JS files 
"db:migrate:run:production": "NODE_ENV=production npx typeorm-ts-node-commonjs migration:run -d ./src/ormconfig.ts",

**Comment by maryjaf** [comment]
should this issue test from QA side? If yes please add more data

**Comment by ae2079** [comment]
@maryjaf 
I think it doesn't need any tests, if staging is working and no problem exists (like today's server internal error), it is ok.

**Comment by ae2079** [comment]
I just merged it and successfully deployed it on staging and it seems ok

**Comment by ae2079** [comment]
It seems there is an issue with running migration files in staging because of merging a PR related to this issue, And @mohammadranjbarz reverted it to fix staging migrations

**Comment by RamRamez** [comment]
@mohammadranjbarz is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz is this issue still relevant?

I think we can ignore this, as we had problem when @ae2079  implemented it
